{
  "source": "github.com/kubernetes/kubernetes.git",
  "commit": "dc1ec1211e4",
  "artifacts": [
    "kubernetes-server-linux-ppc64le.tar.gz",
    "kubernetes-test-linux-ppc64le.tar.gz",
    "kubernetes-client-linux-ppc64le.tar.gz"
  ],
  "project": "kubernetes/master/golang/master"
}