{
  "source": "github.com/kubernetes/kubernetes.git",
  "commit": "f9f00da6bcc",
  "artifacts": [
    "kubernetes-test-linux-ppc64le.tar.gz",
    "kubernetes-client-linux-ppc64le.tar.gz",
    "kubernetes-server-linux-ppc64le.tar.gz"
  ],
  "project": "kubernetes/master/golang/master"
}